### ISSUE TITLE
Kernel panic in Ubuntu 14.04

### ISSUE THREAD

**Issue by hotice** [Douane/douane-dkms#3] opened 2014-04-29 13:48 UTC
douane-dkms causes Kernel panics in Ubuntu 14.04 64bit. This seems to occur randomly, while browsing some websites in Firefox for instance (so not on boot).

I'm using the Ubuntu Linux 3.13.0-24-generic Kernel.

**Comment by zedtux** [comment] 2015-04-26 20:27
I've switched to Debian and I'm considering trying Douane in order to finally fix this issue.

**Comment by junkvolny** [comment] 2015-04-27 17:24
Yesterday, all I had to do for system freeze was run web browser. Today it worked somehow without freeze for quite some time, but I was able to force system hang with following:
1. open web browser (i used firefox), that has allow rule in place, web page loads
2. stop the daemon with #sudo /etc/init.d/douane stop
3. If not already system hang, repeat deamon start/stop few times, mix in few refreshes in web browser.
Works like charm (irony: system freeze works).

Maybe I should try to watch log of kernel module, not just daemon with #tail -f /var/log/douane.log but not sure how and if it's enabled by default, in any case, if you can reproduce freeze with these steps, you might be better at it.

**Comment by junkvolny** [comment] 2015-04-27 19:46
I did huge amount of searching today for possible alternatives today, and I found GPLed project http://sourceforge.net/projects/leopardflower/ that uses iptables and libnetfilter_queue, thus it does not require kernel module (!). I must admit I have not tested it much. I think all these troubles are because kernel module is so hard to debug. 

Your "Douane personal firewall" and mentioned "Leopard flower per-application (personal) firewall" are the only application firewalls for current Linux/Ubuntu out there, I am afraid.

**Comment by arlsr** [comment] 2015-04-27 20:10
leopardflower has plenty of issues of its own sadly, but none that crash the host.

**Comment by zedtux** [comment] 2015-04-28 20:17
As I'm now using Debian (no more Ubuntu), I will now test it with Debian.

**Comment by zedtux** [comment] 2015-04-29 18:24
Alright, I have a working Debian in VirtualBox (I have updated the dependencies wiki page for Debian) and I got the crash and the crash dump file has been generated.

I'm giving a look now.

**Comment by zedtux** [comment] 2015-04-29 18:35
OK now I see the issue. The freeze come from an issue in the kernel module communication with the daemon.

Simple things like `ping` are working like a charm while a lot of activity is making the freeze happening. I will try to solve this in my free time...

**Comment by zedtux** [comment] 2015-04-30 05:50
@junkvolny @arlsr @ho-mo I have created the branch fix-kernel-freeze where I did modification which allowed me to use Douane in a VM. After 15m the VM slow down and the `douane-dialog` process was using 100% of the CPU so I need to have a look to this but at least the kernel freeze is gone for now.

**Comment by junkvolny** [comment] 2015-04-30 19:46
I tested today, on same virtual machine that was freezing before, and yes, it seems the kernel freeze is gone, well done.

I didn't test long run, for dialog-process freeze, but to be honest, dialog is least important component - it cannot crash kernel + if it crashes, it does not stop daemon from enforcing rules, hopefully.

**Comment by zedtux** [comment] 2015-05-01 10:38
> ... if it crashes, it does not stop daemon from enforcing rules, hopefully.

You're right, it do not.

I have already identified in the issue Douane/douane-daemon#6 that the daemon is increasing the memory usage and after an amount of time is using all the memory so I need to fix it.

**Comment by arlsr** [comment] 2015-09-20 09:39
@zedtux I got a freeze while installing, probably because I didn't remove the old version but after that no freezes in the several hours I've tested so far. I'll give it more time and report back. Great work fixing it if it is fixed!

**Comment by zedtux** [comment] 2015-09-20 09:47
:+1: thank you @arlsr. I would love to get some feedback from you :)

**Comment by arlsr** [comment] 2015-09-21 18:28
No issues after 24 hours, I think it's fixed :100:

**Comment by arlsr** [comment] 2015-10-03 18:52
I had a freeze while sending a lot of traffic. I've unloaded the kernel module again.

**Comment by smarek** [comment] 2016-04-26 23:17
I finally struggled with this too, on Debian 8 x86_64 with kernel 4.4

I can reproduce the problem with 100% success rate, by running `nmap -T4 -A MY_PUBLIC_IP`

Sincerely, it seems my kdump config does not work currently, so I'll try to obtain proper crashdump, so far I have only photo of screen of crashed machine, with stack trace and point to `netfiler_packet_hook.isra.5` within douane kernel module

**Comment by smarek** [comment] 2016-04-27 10:48
I've also tried with patch provided in branch **fix-kernel-freeze** but the behavior remains the same

**Comment by zedtux** [comment] 2016-04-27 12:06
There should be a problem of something `free`d to earlier (especially when pushing messages from the kernel space to the user space).
But this needs to be debug with `gdb` and `crash`.

Then the next issue to solve will be the daemon memory usage. The daemon is storing too much messages coming from the kernel space and no deleting them apparently.

**Comment by zedtux** [comment] 2016-04-27 12:06
@smarek the **fix-kernel-freeze** branch has been merged to master and should be deleted.

**Comment by smarek** [comment] 2016-04-28 14:00
@zedtux thanks for info, I'm trying to get hold of crashdump, however there is no /proc/vmcore which is apparently needed for kdump-tools (try `kdump-config savecore`), do you maybe have any idea how to get kernel crash dump working or debug why it is not working?

**Comment by zedtux** [comment] 2016-04-28 14:05
@smarek have you tried to follow my blog article http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/ ?

**Comment by smarek** [comment] 2016-04-28 14:54
@zedtux yes, kdump-tools configured (except for the savecore command not working), ubuntu `linux-crashdump` is not available, forcing crash will result in panic on tty1 not in dump in /var/crash (this folder contains only kexec_cmd file). So I cannot say that your blog helped me, but you've mentioned migrating to Debian, that's why I asked in the first place

**Comment by zedtux** [comment] 2016-04-28 14:58
I did that blog article while I was running Ubuntu, and since I've migrated to Debian. I should take the time to redo this and do another blog article for Debian this time...
So I don't know how to help you now.

**Comment by zedtux** [comment] 2016-04-28 15:03
Regarding the `linux-crashdump` from Ubuntu, it's nothing else than a meta package (see http://packages.ubuntu.com/xenial/linux-crashdump) installing the packages `grub-pc`, `kdump-tools` and `crash`.
The `apport` package is an Ubuntu specific package which we don't care about.

So the Debian equivalent of `sudo apt-get install linux-crashdump` is `apt-get install grub-pc dump-tools crash`

**Comment by zedtux** [comment] 2016-05-05 19:10
@smarek here is another blog article explaining how to install KDump on Debian : https://www.bentasker.co.uk/documentation/linux/312-installing-and-configuring-kdump-on-debian-jessie.

I just tried it but unfortunately, I can't get my system booting a kernel after the panic ... I don't know yet why.

**Comment by zedtux** [comment] 2016-08-09 05:48
@hotice, @pavlinux @ho-mo, @arlsr, @junkvolny and @smarek I have merged @Guimli's PR this morning which fixes a lot of issues and seems to have fixed the kernel freezes! (I tested it over the week-end without freezes).

Can you please `pull` the master branch of this repo, rebuild the module and give me your feedbacks?

**Comment by hotice** [comment] 2016-08-12 10:59
I'm not using Ubuntu 14.04 any more. In Ubuntu 16.04, douane-daemon and douane-dialog fail to build. Here are the builds in my test PPA: https://launchpad.net/~nilarimogard/+archive/ubuntu/test2/+packages?field.name_filter=&field.status_filter=published&field.series_filter=xenial

Looking at my earlier comments, just installing the dkms module doesn't trigger the issue, the daemon must be running...

**Comment by zedtux** [comment] 2016-08-12 11:37
You're build issue is coming from your packing. The daemon and dialog needs to be cloned using the `--recursive` flag in order to download the sub modules too. See the documentation https://github.com/Douane/Douane/wiki/Compilation#the-daemon.

**Comment by hotice** [comment] 2016-08-12 15:09
Oh, I missed that, sorry. Everything builds now. However, the douane-dialog which is supposed to let me allow access for apps to use the Internet, never shows up.  I tried restarting the session, etc., nothing seems to work. Maybe something changed in Ubuntu 16.04 that prevents it from working?

**Comment by zedtux** [comment] 2016-08-12 15:12
Nope, it's working for me with that version of Ubuntu.

Can you please have a look at the `/var/log/douane.log` and `/var/log/kern.log` files?
You can also run the dialog progress in debug mode using the `-D` flag.

I'm there to help you if you need :)

**Comment by hotice** [comment] 2016-08-15 12:40
It looks like the only way to get douane-dialog to show up is to run it manually, but then it segfaults after about 1 second. Even in debug mode, it doesn't display anything. I did get it once to display an output (without the debug flag):
```
**
Gtk:ERROR:/build/gtk+3.0-6ZPWga/gtk+3.0-3.18.9/./gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
**
Gtk:ERROR:/build/gtk+3.0-6ZPWga/gtk+3.0-3.18.9/./gtk/gtkcssinheritvalue.c:33:gtk_css_value_inherit_free: code should not be reached
```

**Comment by zedtux** [comment] 2016-08-16 21:01
Well that's strange. As I said, I have a VM of Ubuntu 16.04.1, all up-to-date and I have the dialog showing up.

Now it is true that I'm always running the app in debug mode, launched manually, it's a long time ago I didn't tried the _normal_ way.

The dialog process is a little buggy, but it shouldn't crash the next second after you've started it.
I can see in the log you have accepted at least a rule.
The worst I saw is the dialog is freezing and I had to kill it and restart it again.

Anyway I need time to improve the daemon process (consuming memory more and more overtime) and the dialog process needs to stability.

Douane is not yet ready to be used everyday, my comment to you @hotice was to show you the progresses done on the kernel module, meaning the project is not dead :)

**Comment by zedtux** [comment] 2018-04-22 06:30
@Mato-Z can you please give more information? What is the ouput of `lsb_release -a` and `uname -a`?

**Comment by Mato-Z** [comment] 2018-04-22 08:52
@zedtux Thanks. 
uname -a:
`Linux mato-pc2 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux`
lsb_release -a:
```
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
```

**Comment by zedtux** [comment] 2018-06-13 11:01
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/douane-dkms/issues/3).

**Closed** 2019-02-14 14:50 UTC
Labels: bug
